name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Python with the specified version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies with compatible versions
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install numpy==1.24.4 librosa==0.10.2 tensorflow==2.9.1
          pip install speechrecognition==3.8.1

      # Step 4: Run Pylint
      - name: Analyze the code with pylint
        run: |
          pylint $(git ls-files '*.py')
