name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]  # You can specify the Python versions here

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Python with the specified version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install the dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint numpy librosa tensorflow speech_recognition websockets

      # Step 4: Run Pylint
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
